Bug Fix added componentWillUnmount to click component
video-react/video-react pull request #323
Opened 2019-11-26 20:58 UTC by joselycas

video-react is taking over the spacebar and not letting users add spaces to text input fields.

2019-11-26 22:19 UTC, joselycas commented
video reproduction of spacebar issue when putting in text.

https://www.loom.com/share/96fe17934db948f298ec4fd1e2d8f1ba

2020-03-25 13:35 UTC, merged

2020-03-25 13:35 UTC, mondaychen commented
Thanks for making contribution!

2022-05-05 02:21 UTC, alsaeyd000077 commented
​  ​"name"​: ​"​arkui​"​, 
 ​  ​"description"​: ​"​Basic UI components for Douban Read.​"​, 
 ​  ​"version"​: ​"​1.0.4​" 
 ​}

2022-05-05 02:22 UTC, alsaeyd000077 requested changes
@mondaychen @joselycas